# Implementation {#implementation}

## Climate and landscape input

a.  Calculation of Drought Index

b.  Calculation of GDD

c.  Slope and aspect

d.  Soil bucket size

e.  Landtype masks

f.  Climate input file (calculation of lapse rates etc.)

### ASCII files

LandClim requires a series of maps as input files. Please note: all maps have to have the same extent and resolution (i.e., ncols, nrows, corners and cellsize). 'No Data' is defined as -9999 in the example files. The cellsize is typically set to 25 (i.e. 25m x 25m).

LandClim requires the following maps which specify topography, soil and further landscape conditions:

-   **Elevation (m a.s.l.)** DEM

-   **Slope (degree)**

-   **Aspect (degree)**

-   **Soil** ('water holding capacity of the soil' or 'bucket size', in cm) : For the calculation of soil water holding capacity, please refer to the following publication: Henne et al. (2011)

-   **Mask:** The 'mask' map (e.g., 'Mask.txt') defines the part of the study landscape to be included in the simulation (e.g., areas above treeline could be excluded to improve runtime). Active cells are labeled '1', inactive cells ~~as '0' here.~~ as -9999 in LandClim 2.0.0, in posterior LandClim versions inactive cells have value 0.

-   **Landtypes:** The map for 'landtypes' (e.g., 'Landtype.txt') allows to assign different landscape-parameters to specific areas (e.g., browsing pressure). For more details about the landtypes, please refer to the following publication: Schumacher et al. (2004)

All maps have to be provided in an ASCII-type raster grid. The basic structure of the ASCII raster has the header information at the beginning of the file followed by the cell value data. The spatial location of the raster is specified by the location of the **lower left cell**, and either 

The topographic maps (elevation, slope and aspect) can be calculated directly from a digital elevation model (see Tutorial 'Initialize map' from Tim!! ).

### Spatial considerations in LandClim

#### Rows and columns

LandClim spatial input files are rasters. The location of each cell is defined by the row or column where it is located within the raster matrix. Essentially, the matrix is represented by a Cartesian coordinate system, in which the rows of the matrix are parallel to the x-axis and the columns to the y-axis of the Cartesian plane. Row and column values begin with 0.

*ADD A DRAWING HERE*

#### Projection

LandClim does not consider projection when the data is entered it is not projected and the coordinates of the different cells are assigned by summing the cell sizes counting from the information provided in the ASCII files (xllcorner and yllcorner) that indicates the coordinates of the

The basic structure of the ASCII raster has the header information at the beginning of the file followed by the cell value data. The spatial location of the raster is specified by the location of the lower left cell, and either 

xllcorner 2695870

yllcorner 1259420

#### Active cells

The active cells are defined in the

#### Cell number

LandClim assign two category of cell numbers internally

#### Y and X coordinates

### **TreeInit / Output files structure**

Table with the information of tree initialization per cell. Each row represent one cohort, several cohorts might be present in the same cell.

#### **Variables definitions**

**id**: ???

**row**: Number of row cell where the cohort is located, the first row is number 0, the counting starts on the upper left corner

**col**: Number of row cell where the cohort is located, the first column is number 0, the counting starts on the upper left corner

**cell**: Number of cell where this cohort is present, the cell counting starts from the upper left corner and goes by row left to right, starting on the number 0, for a landscape of 5X2, the first row will cointain the cells: 0,1,2,3,4 and the second: 5,6,7,8,9. The cell number only counts for active cells!

**xcoord**: Location of the cohort in \[m\], counted from the beginnning of the UTM zone where the landscape is located, bottom left corner of the area, this information is provided in the ASCII initial files

**ycoord**: Location of the cohort in \[m\], counted from the beginnning of the UTM zone where the landscape is located, bottom left corner of the area, this information is provided in the ASCII initial files

**landtype**:

**elevation**

**species**: Name of the species in shortenend version with 8 characters ( "abiealba" "larideci" "piceabie" "pinucemb" "pinusilv" "acerpseu" "betupube" "fagusilv" "popunigr"  "querpetr" "querrobu" "sorbaucu" "alnuinca" "alnuviri" "poputrem" "salicapr" "acercamp" "acerplat" "alnuglut" "betupend" "carpbetu" "castsati" "coryavel" "fraxexce" "querpube" "salialba" "sorbaria" \[28\] "tilicord" "tiliplat" "ulmuglab" "ilexaqui" "grass")

**age**

**biomass**

**stems**

**slowGrowth**

**slowGrowthLight**

**slowGrowthWater**

**slowGrowthTemp**

**DBH**: from 8 cm???

**height**:

**availableLight**

**light_rf**

**LeafArea**

**nitorgen_rf**

**droughtIndex**

**moisture_rf**

**degreeDay_rf**

**foliageWght,**

**twigWght**

**boleWght**

**deadFoliage**

**deadTwig**

**deadbole**

**Mortality**

### **Species-configuration XML**

The plant species and parameters is pass to LandClim through the file called *species-configuration* in the test files set.

This file is the setup for all the central European especies, its values are based on literature according to Schumacher et al. (2004) ??? Herbaceous species are also included here. WHY THIS IS AN XML IF IT IS NOT MODIFICABLE???

Each grid cell contains information at the espeices level. Vegetation status is defined by the presence/absence data of 10-year age cohorts of each species.

For each species, a **set of attributes** such as longevity, age of first reproduction, shade and fire tolerance, and seeding distance are driving vegetation dynamics.

The **establishment of new tree cohorts** is modeled based on seed availability and a simple parameterization of light and site conditions (Mladenoff and He, 1999).

**Seed availability** is determined by seed travel distances and the age of maturity of each tree species. Seed travel distance is defined by species specific effective and maximum parameters (He and Mladenoff, 1999a).

Species' differences in their ability to reproduce vegetatively after disturbances are also taken into account in the model. For successful **establishment**, propagules have to be available in the grid cell, and light conditions have to be favorable. Species can establish only if they are more shadetolerant than any other species that is already occurring in the grid cell.

#### **List of species file parameters**

**Name**: Name of the species in shortenend version with 8 characters ( "abiealba" "larideci" "piceabie" "pinucemb" "pinusilv" "acerpseu" "betupube" "fagusilv" "popunigr"  "querpetr" "querrobu" "sorbaucu" "alnuinca" "alnuviri" "poputrem" "salicapr" "acercamp" "acerplat" "alnuglut" "betupend" "carpbetu" "castsati" "coryavel" "fraxexce" "querpube" "salialba" "sorbaria" \[28\] "tilicord" "tiliplat" "ulmuglab" "ilexaqui" "grass") **PlantForm**: TREE / HERBACEOUS **MaxAge**: expected longevity (Bugmann, 1994) \[year\] **AgeAtMaturity**: maturity age for seed production (Rohmeder, 1972, p. 35) **ShadeTolerance**: species shading tolerance (ordinal number between 1 and 5, 1 denotes least shade-tolerant) (Ellenberg, 1996 p. 119) **FireTolerance**: 1:5 Ref??? **WindthrowTolerance** : 1:3 Ref?? **EffectiveDispersalDistance**: effective seeding distance \[m\] **MaxDispersalDistance**: maximum seeding distance (Rohmeder, 1972) \[m\] **VegetativeReproductionProbability**: probability of vegetative reproduction

**MaxAgeForVegetativeReproduction**: maximum age for vegetative reproduction (Burschel and Huss, 1997) **RMax**: maximum above-ground biomass growth rate (Flury, 1895; Burger, 1945, 1947, 1948, 1950a,b, 1951, 1952, 1953; Anonymous, 1983; Schober, 1987; Lick and Sterba, 1991; Hillebrand, 1997) \[t??? year−1\] **KMax**: maximum aboveground tree biomass a species can potentially reach (Assmann, 1961; Grosser, 1977; Burger, 1945, 1947, 1948, 1950a,b, 1951, 1952, 1953; Bugmann, 1994) \[t???\] **MaxHeight** : \[m\] Ref??? **LeafHabit**: "HERBS" "EVERGREEN" or "DECIDUOUS" Ref??? **FoliageType**: Foliage type (Bugmann, 1994) **MinDegreeDays**: minimum annual degree-day sum (Bugmann, 1994) **MinTemperature**: minimum temperature for establishment (Bugmann, 1994) **DroughtTolerance**: drought tolerance of species (1, very intolerant; 5, very tolerant) (Bugmann, 1994; Bugmann and Cramer, 1998) **BrowsingTolerance**: browsing tolerance (Bugmann, 1994) **GrazingTolerance**: 0-2? Ref?? **GrazingToleranceRank** : 1:6 Ref?? **GrowthModel**: LOGISTIC, growth model is based on the a priori assumption of a logistic growth relation for the isolated plant (Schumacher et al. 2004) **CrownShape**: 1:6 Ref???

**HerbaceousForm** : GRASS Ref???

**LifeCycleType** : PERENNIAL Ref???

### **Landtype parameters XML**

Each grid cell belongs to a different *Land type*. These user defined land types are the basis for distinguishing between different site characteristics, environmental conditions, and species-specific establishment probabilities. Site parameters can be defined by **ecoregions** (land types).

#### Description of the land type parameters

Per each land type we need to define the following

##### Id

Usually a number that defines the land type number in order e.g. 1, 2, etc

##### Name

A character that describes the land type, it could be empty / active e.g. NE, SW

##### MinShadeYears

30

##### MeanFireReturnInterval

3000

##### FireIgnitionCoefficient:

0.002

##### IgnitionCoefficient:

0.002

##### fireProbabilityCoefficient

20

##### lastWindthrowDisturbance

400

##### lastFireDisturbance

400

##### browsingIntensity

0.2

##### potentialSaplingDensity

0.5

##### defaultEstablishmentCoefficient

0.9 for all the species expect the one defined in the category "speciesEstablishmentCoefficients"

##### speciesEstablishmentCoefficients:

###### name

piceabie

###### establishmentCoefficient

0.9

###### vegetativePropagules

0.9 for all the species

##### defaultVegetativePropagules

for all the species

##### maxBiomassDensity

    <Id>2</Id>
        <Name>SW</Name>
        <MinShadeYears>30</MinShadeYears>
        <MeanFireReturnInterval>3000</MeanFireReturnInterval>
        <FireIgnitionCoefficient>0.0002</FireIgnitionCoefficient>
        <FireProbabilityCoefficient>20</FireProbabilityCoefficient>
        <LastWindthrowDisturbance>400</LastWindthrowDisturbance>
        <LastFireDisturbance>400</LastFireDisturbance>
        <BrowsingIntensity>0</BrowsingIntensity>
        <PotentialSaplingDensity>0.5</PotentialSaplingDensity>      
        <DefaultEstablishmentCoefficient>0.9</DefaultEstablishmentCoefficient>
        
        <SpeciesEstablishmentCoefficients>
            <SpeciesEstablishmentCoefficient>
                <Name>piceabie</Name>
                <EstablishmentCoefficient>0.9</EstablishmentCoefficient>
                <VegetativePropagules>false</VegetativePropagules>
            </SpeciesEstablishmentCoefficient>
        </SpeciesEstablishmentCoefficients>
        <DefaultVegetativePropagules>false</DefaultVegetativePropagules>
        <MaxBiomassDensity>1000</MaxBiomassDensity>

### **Planting parameters XML**

## The control file

## Set up of the lanscape

## Simulation set up

length, and other parameters

## Tutorials
